# Use root/example as user/password credentials
version: "3.8"                                      # docker-compose version

services:
  mysql:
    container_name: mysql_batch
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d               # {host src} : {container src}
      - ./db/initdb.d:/docker-entrypoint-initdb.d   # sh, sql을 파일명 알파벳순으로 수행, 테이블 create, insert 쿼리 파일 들어있음
    ports:
      - "3306:3306"
    environment:                                    # 환경변수 설정
      - MYSQL_DATABASE=management_batch
      - MYSQL_USER=wook
      - MYSQL_PASSWORD=wook123
      - MYSQL_ROOT_PASSWORD=wook123
      - TZ=Asia/Seoul
