spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/management_batch?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: wook
    password: wook123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:          # HikariCP 설정 # 스프링부트 2.0 부터 tomcat dbcp -> hikari dbcp 로 변경, 사용하지 않는 커넥션은 회수하도록 설계됨
      maximum-pool-size:  20

  batch:
    jdbc:
      initialize-schema: always # 자동생성
